name: react
# Contrôle quand le workflow démarre :
on:
  # sera lancé manuellement :
  workflow_dispatch:
    # l'action choisie nécessite le paramètre sync :
    inputs:
      sync:
        default: delta
  # un workflow est une liste de tâches :
jobs:
  react:
    runs-on: ubuntu-latest
    steps:
      - name: build react
        run: |
          cd front
          npm install
          npm run build
      - name: téléversement SFTP du react
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: kiliangui.fr
          remote-user: ${{secrets.user}}
          remote-password: ${{secrets.password}}
          remote-path: /var/www/front
          local-path: ./build